version: '3'
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db

  backend:
    build: ./back-end
    ports:
      - "8070:8070"   
    volumes:
      - logs:/app/logs
      - ./back-end:/app
      - /app/node_modules    
    depends_on:
      - mongodb

  frontend:
    build: ./front-end
    ports:
      - "3000:3000"  
    volumes:
      - ./front-end/src/app:/src
    stdin_open : true
    
    depends_on:
      - backend
volumes:
  data: 
  logs: